services:
  app:
    image: fastapi-book-server
    build: .
    ports:
      - 8000:8000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080
    container_name: reverse-proxy
    depends_on:
      - app
