name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: actions/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          scripts: |
            # update system
            sudo apt-get update -y

            # Install docker
            sudo apt install -y ca-certificates curl gnupg
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update
            sudo apt install -y docker-ce docker-ce-cli containerd.io

            sudo usermod -aG docker ubuntu


            # Start Docker service
            sudo systemctl start docker
            sudo systemctl enable docker

            # Install Docker compose
            sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d'"' -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

            sudo chmod +x /usr/local/bin/docker-compose

            # Verify installations
            docker --version
            docker-compose --version

            # Navigate to directory
            cd /home/ubuntu

            # Pull latest lates code from github
            git pull origin main

            #Deploy app
            sudo docker-compose up -d --build
