name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          scripts: |
            # update system
            sudo apt-get update -y

            # Install docker
            sudo apt  install docker.io

            sudo usermod -aG docker ubuntu


            # Start Docker service
            sudo systemctl start docker
            sudo systemctl enable docker

            # Install Docker compose
            sudo apt  install docker-compose

            sudo chmod +x /usr/local/bin/docker-compose

            # Verify installations
            docker --version
            docker-compose --version

            # Navigate to directory
            cd /home/ubuntu

            # Pull latest lates code from github
            git pull origin main

            #Deploy app
            sudo docker-compose up -d --build
